### ISSUE TITLE
The 'retention.ms' and 'log.retention.ms' settings have no effect.

### ISSUE THREAD

**Issue by ksimmi** [karafka/karafka#2452]
Hello!

How to configure expiring messages or their equivalent? 

I saw that you have https://karafka.io/docs/Pro-Expiring-Messages/
But I also thought I could achieve a similar result using 'retention.ms' or 'log.retention.ms'.

However, applying both did not help. Here's how I tested: I put several broken messages into the topic that can be processed by the business logic of the application. Then I configured my topic as follows:
```
    topic 'test_upsert' do
      config('retention.ms': 1000, 'log.retention.ms': 1000)
      consumer Broadcasts::TestUpsert
    end
```

But when I restart my application, it starts processing the old broken messages, although an hour has already passed since I put them there.

Perhaps additional settings for Karafka or Kafka are needed?

**Comment by mensfeld** [comment]
> However, applying both did not help.

I'm fairly certain expiring messages feature works. I assume you are referring to the retention.ms and log retention.ms.

On such short spans they will not work.

There are a few potential reasons why your Kafka messages aren't being deleted after 1 second despite setting those retention parameters:

- Kafka's log retention cleanup doesn't run continuously. By default, the log.cleanup.interval.ms is set to 5 minutes (300000 ms). This means that even if you set a 1-second retention period, the cleanup thread will only check and delete eligible messages every 5 minutes.

- The actual deletion process is subject to various conditions:
  - Kafka won't delete segments that are currently active (being written to)
  - There must be at least one segment remaining after deletion
  - The segment file must be fully rolled before it can be considered for deletion

**Comment by mensfeld** [comment]
> How to configure expiring messages or their equivalent?

- For long periods the way you did with appropriate Kafka cluster tuning.
- For short by using the feature you mentioned or by doing manual work needed to do that yourself.
-

**Comment by mensfeld** [comment]
I updated the docs to highlight this difference.

**Comment by ksimmi** [comment]
Thank you for the response. Initially, I set 30 seconds using only retention.ms. The example where I use 1 second and additionally specify the log.retention.ms option was just my last experiment. 

Did I understand correctly that the implementation of Kafka itself will not allow deleting messages newer than 5 minutes?

**Comment by ksimmi** [comment]
I just set retention.ms to 1_000_000 and I'm still receiving messages that I put in on Friday.
```
    topic 'test_upsert' do
      config('retention.ms': 1_000_000)
      consumer Broadcasts::TestUpsert
    end
```
I stopped the application that was publishing messages to Kafka. Therefore, I can now be sure that no write operations are happening in Kafka.

**Comment by mensfeld** [comment]
> Did I understand correctly that the implementation of Kafka itself will not allow deleting messages newer than 5 minutes?

Among others yes. In theory it could but such aggressive segment rotation is not something I would recommend.

> I just set retention.ms to 1_000_000 and I'm still receiving messages that I put in on Friday.

This is something controlled by your kafka settings. Let me assure you that under correct settings the retention management kicks in correctly and in write times. FYI as I said above - the fact that you stopped means nothing because this is not how retention policies are applied in Kafka, especially in regards to the current data segment (described above).
